"""add spans table

Revision ID: bc901726b61d
Revises: 4eea0dde00fc
Create Date: 2026-08-10 20:31:17.418781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc901726b61d'
down_revision: Union[str, Sequence[str], None] = '4eea0dde00fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('parent_span_id', sa.String(length=32), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('span_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_task_id'), 'spans', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spans_task_id'), table_name='spans')
    op.drop_table('spans')
    # ### end Alembic commands ###
